import Head from "next/head";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

const FooterWrapper = styled.div`
  width: 100%;
  height: 50px;
  border: 3px solid red;
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next + Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
    </div>
  );
}
